### ISSUE TITLE
User-reported Bug: analysis input type is not consistent with value type

### ISSUE THREAD

**Issue by XinhuiLi** [ReproNim/regtests#110]
**Bug Description**
In `testkraken/workflows4regtests/cpac/anat_preproc/testkraken_spec.yml`, when a directory is offered as analysis input, the type "Directory" doesn't work and it has be changed to "File". For example,

```
analysis:
  script: anat_preproc.py
  command: python
  inputs:
  - {type: Directory, argstr: -i, value: .}
```

Here, the value is the current directory ".", however if we specify the type as "Directory", it doesn't work. It works if we change "Directory" to "File":

```
analysis:
  script: anat_preproc.py
  command: python
  inputs:
  - {type: File, argstr: -i, value: .}
```

**Expected Behavior**
The type should be consistent with the value, so we expect that the first code block should work well.
